hf2ui31b replace delete buttons with delete icons
TeodorBirghisan/vot_senat_client pull request #10
Opened 2022-02-28 20:47 UTC by ConstantinFugaru

Replaced delete button with delete icons for meetings and topics

2022-02-28 22:35 UTC, cezarmocanu requested changes

2022-02-28 22:35 UTC, cezarmocanu commented on lib/widgets/topic_card.dart
> +            Stack(
I appreciate the approach, and it gets the job done, but it has some downsides:
- stacks are meant to render elements in a multi layer fashion (layering from back to front)
- the code here is a bit too bulky for only displaying a title and an icon
- items are not aligned correctly on the vertical axis
- padding is not equally applied around the items

2022-02-28 22:35 UTC, cezarmocanu commented on lib/widgets/topic_card.dart
> +            Stack(
Try the following approach for solving a problem like this

```dart
Padding(
  padding: const EdgeInsets.all(8.0),
  child: Row(
    //this ensures the items from the row are aligned correctly
   //this is equivalent to using display:flex, justify-content: space-between in CSS
    mainAxisAlignment: MainAxisAlignment.spaceBetween,
    children: [
      //this needs to have the same width as the ink well
      const SizedBox(width: 24),
      Text(
        meeting.title ?? "",
        style: Theme.of(context).textTheme.subtitle2,
      ),
      Material(
        color: Colors.red,
        borderRadius: BorderRadius.circular(24),
        child: InkWell(
          borderRadius: BorderRadius.circular(24),
          child: const Padding(
            padding: EdgeInsets.all(6.0),
            child: Icon(
              Icons.delete,
              color: Colors.white,
              size: 18,
            ),
          ),
          onTap: () {
            //...
          },
        ),
      ),
    ],
  ),
),
const Divider(height: 1),
```

2022-02-28 22:39 UTC, cezarmocanu commented on lib/widgets/topic_card.dart
> +            Stack(
Following the previous code yields this result:
<img width="371" alt="Screenshot 2022-03-01 at 00 37 23" src="https://user-images.githubusercontent.com/15773819/156070210-16d9d7ae-2102-4438-9b4b-72680bd31b83.png">

As opposed to:
<img width="371" alt="Screenshot 2022-03-01 at 00 38 55" src="https://user-images.githubusercontent.com/15773819/156070285-904cccba-6e80-44f0-9359-46c82f8b1a68.png">

2022-03-01 10:42 UTC, TeodorBirghisan commented
Right now, you will merge this into main. 
**Please change the merging branch into dev.**
**In the feature, create all your branches from the dev branch.**
Changes will be merged in main only when they are ready to be deployed.

2022-03-02 20:05 UTC, cezarmocanu approved these changes

2022-03-02 20:05 UTC, merged